module.exports = {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    screens: {
      'xs': '375px',
      'sm': '640px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1280px',
      '2xl': '1536px',
      '3xl': '1920px',
    },
    extend: {
      fontSize: {
        'fluid-xs': 'var(--fluid-xs)',
        'fluid-sm': 'var(--fluid-sm)',
        'fluid-base': 'var(--fluid-base)',
        'fluid-lg': 'var(--fluid-lg)',
        'fluid-xl': 'var(--fluid-xl)',
        'fluid-2xl': 'var(--fluid-2xl)',
        'fluid-3xl': 'var(--fluid-3xl)',
        'fluid-4xl': 'var(--fluid-4xl)',
        'fluid-5xl': 'var(--fluid-5xl)',
        'fluid-6xl': 'var(--fluid-6xl)',
      },
      spacing: {
        'fluid-1': 'var(--fluid-space-1)',
        'fluid-2': 'var(--fluid-space-2)',
        'fluid-3': 'var(--fluid-space-3)',
        'fluid-4': 'var(--fluid-space-4)',
        'fluid-5': 'var(--fluid-space-6)',
        'fluid-6': 'var(--fluid-space-6)',
        'fluid-8': 'var(--fluid-space-8)',
        'fluid-10': 'var(--fluid-space-10)',
        'fluid-12': 'var(--fluid-space-12)',
        'fluid-16': 'var(--fluid-space-16)',
        'fluid-20': 'var(--fluid-space-20)',
        'fluid-24': 'var(--fluid-space-24)',
      },
      gap: {
        'fluid-xs': 'var(--fluid-gap-xs)',
        'fluid-sm': 'var(--fluid-gap-sm)',
        'fluid-md': 'var(--fluid-gap-md)',
        'fluid-lg': 'var(--fluid-gap-lg)',
        'fluid-xl': 'var(--fluid-gap-xl)',
        'fluid-2xl': 'var(--fluid-gap-2xl)',
      },
      padding: {
        'fluid-xs': 'var(--fluid-padding-xs)',
        'fluid-sm': 'var(--fluid-padding-sm)',
        'fluid-md': 'var(--fluid-padding-md)',
        'fluid-lg': 'var(--fluid-padding-lg)',
        'fluid-xl': 'var(--fluid-padding-xl)',
        'fluid-2xl': 'var(--fluid-padding-2xl)',
      },
      margin: {
        'fluid-xs': 'var(--fluid-space-1)',
        'fluid-sm': 'var(--fluid-space-2)',
        'fluid-md': 'var(--fluid-space-4)',
        'fluid-lg': 'var(--fluid-space-6)',
        'fluid-xl': 'var(--fluid-space-8)',
      },
      borderRadius: {
        'fluid-sm': 'var(--fluid-radius-sm)',
        'fluid-md': 'var(--fluid-radius-md)',
        'fluid-lg': 'var(--fluid-radius-lg)',
        'fluid-xl': 'var(--fluid-radius-xl)',
        'fluid-2xl': 'var(--fluid-radius-2xl)',
      },
      flex: {
        '1': '1 1 0%',
        'auto': '1 1 auto',
        'initial': '0 1 auto',
        'none': 'none',
      },
      flexGrow: {
        '0': '0',
        'DEFAULT': '1',
      },
      flexShrink: {
        '0': '0',
        'DEFAULT': '1',
      },
    },
    borderColor: ({ theme }) => ({
      ...theme("colors"),
      DEFAULT: "var(--border)",
    }),
  },
  plugins: [],
};